apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: kube.squatch.dev/dev-immich.database-user
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: kube.squatch.dev/dev-immich.database-user
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
