# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   annotations:
#     pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
#   name: immich-library-pv
# spec:
#   capacity:
#     storage: 256Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: csi-nfs-nas-media
#   mountOptions:
#     - nfsvers=4.1
#   csi:
#     driver: nfs.csi.k8s.io
#     volumeHandle: jrm-nas-01.squatch.dev#immich#media
#     volumeAttributes:
#       server: jrm-nas-01.squatch.dev
#       share: /volume1/media/immich
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: immich-library-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 256Gi
#   volumeName: immich-library-pv
#   storageClassName: csi-nfs-nas-media

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.129.10.1
    path: /volume1/media/immich
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  volumeName: immich-library-pv
