name: trek

services:
  server:
    image: mauriceboe/trek:latest
    restart: unless-stopped
    networks:
      - public-trek
    expose:
      - 3000
    environment:
      NODE_ENV: production
      TZ: America/New_York
      ALLOWED_ORIGINS: https://trek.squ4tch.net,https://trek.squatch.dev
      TRUST_PROXY: 1 # Number of trusted proxies for X-Forwarded-For
      ALLOW_INTERNAL_NETWORK: true
      APP_URL: https://trek.squatch.dev
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    labels:
      traefik.enable: true
      traefik.docker.network: public-trek
      traefik.http.routers.trek.rule: Host(`travel.squ4tch.net`) || Host(`travel.squatch.dev`)
      traefik.http.routers.trek.entrypoints: websecure
      traefik.http.routers.trek.tls: true
      traefik.http.routers.trek.tls.certresolver: le
      traefik.http.services.trek.loadbalancer.server.port: 3000
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    tmpfs:
      - /tmp:noexec,nosuid,size=64m
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 256M
          pids: 64
        reservations:
          cpus: 0.05
          memory: 64M

networks:
  public-trek:
    name: public-trek
    external: true
