apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: cert-manager
    namespace: cert-manager
    name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.18.2
    valuesFile: values.yaml

resources:
  - cluster-issuer-staging.yaml
  - cluster-issuer-production.yaml
  - token-secret.yaml
