apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: kube.squatch.dev/cert-manager.cloudflare-api-token
        property: password
