apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: kube.squatch.dev/synology-csi.client-info
        property: client-info.yml
