apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: synology-csi
    namespace: synology-csi
    name: synology-csi
    repo: https://zebernst.github.io/synology-csi-talos
    version: 0.9.4
    valuesFile: values.yaml

resources:
  - credentials-secret.yaml
  - namespace.yaml
