{{- range $name, $secret := .Values.secrets -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    {{- range $secret.data }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .opItem.title }}
        property: {{ .opItem.label }}
    {{- end }}
---
{{- end -}}
