apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: kube.squatch.dev/dev-homarr.db-secret
        property: db-encryption-key
