apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op-secret-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://op-connect.op-connect.svc.cluster.local:8080
      vaults:
        squatch-lan: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-connect-token
            namespace: external-secrets
            key: token
