apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: external-secrets
    namespace: external-secrets
    name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.18.2

resources:
  - cluster-secret-store.yaml
  - token-secret.yaml
