apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: op-connect-token
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: kube.squatch.dev/external-secrets.op-connect-token
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
