apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: op-credentials
  namespace: op-connect
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: 1password-credentials.json.b64
      remoteRef:
        key: kube.squatch.dev/op-connect.op-credentials
        property: 1password-credentials.json.b64
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
