apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: op-connect
    namespace: op-connect
    name: connect
    repo: https://1password.github.io/connect-helm-charts/
    version: 1.17.0
    valuesFile: values.yaml

resources:
  - credentials-secret.yaml
  - http-route.yaml
