apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
    - name: cilium-bgp
      localASN: 64513
      peers:
        - name: router
          peerASN: 64512
      peerAddress: 10.129.0.1
      peerConfigRef:
        name: cilium-peer
