apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
    - name: cilium-bgp
      localASN: 65001
      peers:
        - name: unifi
          peerASN: 65000
          peerAddress: 10.129.0.1
          peerConfigRef:
            name: unifi
