apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: border-services-internal-pool
spec:
  blocks:
  - cidr: 10.128.0.1/20
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: border-services-external-pool
spec:
  blocks:
  - cidr: 10.128.32.1/20
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: management-applications-pool
spec:
  blocks:
  - cidr: 10.129.64.1/20
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: private-applications-pool
spec:
  blocks:
  - cidr: 10.129.128.1/20
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-applications-pool
spec:
  blocks:
  - cidr: 10.129.192.1/20
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: iot-pool
spec:
  blocks:
  - cidr: 10.130.128.1/19
