apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: cilium
    namespace: kube-system
    name: cilium
    repo: https://helm.cilium.io/
    version: 1.18.1
    valuesFile: values.yaml

resources:
  - bgp-advertisement.yaml
  - bgp-peer-config.yaml
  - bgp-cluster-config.yaml
  - ip-pools.yaml
  - http-route.yaml
