! -*- bgp -*-
!
hostname $UDMP_HOSTNAME
password zebra
frr defaults traditional
log file stdout
!
router bgp 65000
 bgp ebgp-requires-policy
 bgp router-id 10.129.0.1
 maximum-paths 2
 !
 neighbor cilium peer-group
 neighbor cilium remote-as 65001
 neighbor cilium activate
 neighbor cilium soft-reconfiguration inbound
 !
 ! Define node IPs as BGP neighbors
 ! These are the nodes running the Cilium BGP speaker
 neighbor 10.129.8.101 peer-group cilium # cerberus-control-plane-01
 neighbor 10.129.8.102 peer-group cilium # cerberus-control-plane-02
 neighbor 10.129.8.103 peer-group cilium # cerberus-control-plane-03
 neighbor 10.129.8.111 peer-group cilium # cerberus-worker-01
 neighbor 10.129.8.112 peer-group cilium # cerberus-worker-02
 neighbor 10.129.8.113 peer-group cilium # cerberus-worker-03
 neighbor 10.129.8.114 peer-group cilium # cerberus-worker-04
 neighbor 10.129.8.115 peer-group cilium # cerberus-worker-05
 neighbor 10.129.8.116 peer-group cilium # cerberus-worker-06
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor cilium activate
  neighbor cilium route-map ALLOW-ALL in
  neighbor cilium route-map ALLOW-ALL out
  neighbor cilium next-hop-self
 exit-address-family
 !
route-map ALLOW-ALL permit 10
!
line vty
!