apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: argocd
    namespace: argocd
    name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.2.5
    valuesFile: values.yaml

resources:
  - http-route.yaml
