apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: homarr
    namespace: homarr
    name: homarr
    repo: oci://ghcr.io/homarr-labs/charts/
    version: 3.8.0
    valuesFile: values.yaml

resources:
  - db-secret.yaml
  - certificate.yaml
  - ingress-route.yaml
