k3s_cluster:
  children:
    load_balancer:
      hosts:
        k3s-lb-01.local.squatch.dev:
          ansible_host: 10.0.30.201
          k3s_load_balancer_role: master
        k3s-lb-02.local.squatch.dev:
          ansible_host: 10.0.30.202
          k3s_load_balancer_role: backup
        k3s-lb-03.local.squatch.dev:
          ansible_host: 10.0.30.203
          k3s_load_balancer_role: backup
    server:
      hosts:
        k3s-server-01.local.squatch.dev:
          ansible_host: 10.0.30.211
        k3s-server-02.local.squatch.dev:
          ansible_host: 10.0.30.212
        k3s-server-03.local.squatch.dev:
          ansible_host: 10.0.30.213
    agent:
      hosts:
        k3s-agent-01.local.squatch.dev:
          ansible_host: 10.0.30.221
        k3s-agent-02.local.squatch.dev:
          ansible_host: 10.0.30.222
        k3s-agent-03.local.squatch.dev:
          ansible_host: 10.0.30.223
        k3s-agent-04.local.squatch.dev:
          ansible_host: 10.0.30.224
        k3s-agent-05.local.squatch.dev:
          ansible_host: 10.0.30.225
        k3s-agent-06.local.squatch.dev:
          ansible_host: 10.0.30.226
  vars:
    ansible_user: squ4tch
    ansible_become_pass: placebo to make ansible happy
    k3s_version: v1.32.2+k3s1
    token: "{{ k3s_cluster_token }}"
    api_endpoint: 10.0.30.200
    cluster_context: squatch-lan-k3s
    extra_server_args: >
      --tls-san "10.0.30.200"
      --disable=servicelb
      --disable=traefik
      --disable=local-storage
      --disable=metrics-server
      --disable-cloud-controller
      --node-taint node-role.kubernetes.io/control-plane:NoSchedule
