apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: userID
      remoteRef:
        key: kube.squatch.dev/ceph-csi-rbd.csi-rbd-secret
        property: userID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: userKey
      remoteRef:
        key: kube.squatch.dev/ceph-csi-rbd.csi-rbd-secret
        property: userKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: userID
      remoteRef:
        key: kube.squatch.dev/ceph-csi-cephfs.csi-cephfs-secret
        property: userID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: userKey
      remoteRef:
        key: kube.squatch.dev/ceph-csi-cephfs.csi-cephfs-secret
        property: userKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
