apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: ceph-csi-rbd
    namespace: ceph-csi-rbd
    name: ceph-csi-rbd
    repo: https://ceph.github.io/csi-charts
    version: 3.14.2
    valuesFile: values.yaml
  - releaseName: ceph-csi-cephfs
    namespace: ceph-csi-cephfs
    name: ceph-csi-cephfs
    repo: https://ceph.github.io/csi-charts
    version: 3.14.2
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - credentials-secret.yaml
  - storage-class.yaml
