apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.14.9
      helm:
        valueFiles:
          - $values/squatch-lan-k3s/infrastructure/metallb/values.yaml
    - repoURL: https://github.com/jacksonmcmath/squatch-lan.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
