apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-route
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik

  hostnames:
    - traefik.kube.squatch.dev

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /dashboard
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: api@internal
          group: traefik.io
          kind: TraefikService

    - matches:
        - path:
            type: PathPrefix
            value: /ping
      backendRefs:
        - name: ping@internal
          group: traefik.io
          kind: TraefikService

    - matches:
        - path:
            type: PathPrefix
            value: /metrics
      backendRefs:
        - name: prometheus@internal
          group: traefik.io
          kind: TraefikService
