apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: traefik
    namespace: traefik
    name: traefik
    repo: https://traefik.github.io/charts
    version: 37.0.0
    valuesFile: values.yaml
  - releaseName: traefik-crds
    namespace: traefik
    name: traefik-crds
    repo: https://traefik.github.io/charts
    version: 1.10.0

resources:
  - http-route.yaml
