apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: traefik
    namespace: traefik
    name: traefik
    repo: https://traefik.github.io/charts
    version: 36.3.0
    valuesFile: values.yaml
  - releaseName: traefik-crds
    namespace: traefik
    name: traefik-crds
    repo: https://traefik.github.io/charts
    version: 1.9.0

resources:
  - httproute.yaml
