providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  listeners:
    web:
      port: 8080
      hostname: "*.squatch.dev"
      protocol: HTTP
      namespacePolicy:
        from: All
    websecure:
      port: 8443
      hostname: "*.squatch.dev"
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - name: squatch-tls
    web-kube:
      port: 8080
      hostname: "*.kube.squatch.dev"
      protocol: HTTP
      namespacePolicy:
        from: All
    websecure-kube:
      port: 8443
      hostname: "*.kube.squatch.dev"
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - name: kube-squatch-tls
    traefik:
      port: 9000
      hostname: "traefik.kube.squatch.dev"
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - name: traefik-tls
    metrics:
      port: 9100
      hostname: "traefik.kube.squatch.dev"
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - name: traefik-tls

ports:
  web:
    port: 8080
    exposedPort: 80
    expose:
      default: true
      internal: true
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    asDefault: true
    port: 8443
    exposedPort: 443
    expose:
      default: true
      internal: true
  traefik:
    port: 9000
    exposedPort: 9000
    expose:
      internal: true
  metrics:
    port: 9100
    exposedPort: 9100
    expose:
      internal: true

service:
  enabled: true
  type: LoadBalancer
  annotations:
    lbipam.cilium.io/ips: "10.129.192.2"
  additionalServices:
    internal:
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: "10.129.128.2"
api:
  dashboard: true

logs:
  general:
    # format: json
    level: DEBUG
  access:
    enabled: true
    addInternals: true
    # format: json

accessLog:
  enabled: true

metrics:
  otlp:
    enabled: true

tracing:
  otlp:
    enabled: true
