services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USERNAME}", "-d", "${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # networks:
    #   - private-***
    expose:
      - 5432
    environment:
      TZ: America/New_York
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - database-data:/var/lib/postgresql
    user: 999:999
    read_only: true
    tmpfs:
      - /var/run/postgresql
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
          pids: 32
        reservations:
          cpus: 0.05
          memory: 16M

  pgvector:
    image: pgvector/pgvector:pg18-trixie
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_USERNAME}", "-d", "${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # networks:
    #   - private-***
    expose:
      - 5432
    environment:
      TZ: America/New_York
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - database-data:/var/lib/postgresql
    user: 999:999
    read_only: true
    tmpfs:
      - /var/run/postgresql
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
          pids: 32
        reservations:
          cpus: 0.05
          memory: 16M

volumes:
  database-data:
    name: ${COMPOSE_PROJECT_NAME}-database-data
