- name: Add Tailscale repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release | lower }}"
    components: main
    signed_by: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.noarmor.gpg"
    state: present
  register: tailscale_repository

- name: Install Tailscale package
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: "{{ tailscale_repository.changed }}"
