- name: Proxmox VE Post Install Configuration
  hosts: pve_nodes
  remote_user: root
  become: false
  gather_facts: false
  roles:
    - role: create_group
      group:
        name: media
        gid: 100900
        system: true
    - role: create_user
      user: "{{ squ4tch_user }}"
    - role: create_user
      user: "{{ jrm_user }}"
  tasks:
    - name: Add non-free repository
      ansible.builtin.copy:
        content: |
          deb http://ftp.us.debian.org/debian bookworm non-free-firmware

          deb http://ftp.us.debian.org/debian bookworm-updates non-free-firmware

          # security updates
          deb http://security.debian.org bookworm-security non-free-firmware

        dest: /etc/apt/sources.list.d/non-free-firmware.list
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    # https://github.com/community-scripts/ProxmoxVE/blob/main/tools/pve/post-pve-install.sh
    - name: Suppress non-free firmware warnings
      ansible.builtin.copy:
        content: |
          APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";

        dest: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Disable ceph enterprise repository
      ansible.builtin.copy:
        content: |
          # deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise

        dest: /etc/apt/sources.list.d/ceph.list
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Disable pve-enterprise repository
      ansible.builtin.copy:
        content: |
          # deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise

        dest: /etc/apt/sources.list.d/pve-enterprise.list
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Enable pve-no-subscription repository
      ansible.builtin.copy:
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    # yamllint disable rule:line-length
    - name: Disable subscription nag
      ansible.builtin.copy:
        content: |
          DPkg::Post-Invoke { "dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ $? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/.*data\.status.*{/{s/\!//;s/active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi"; };

        dest: /etc/apt/apt.conf.d/disable-subscription-nag.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Enable high availability services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - pve-ha-lrm
        - pve-ha-crm
        - corosync

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - coreutils
          - curl
          - git
          - intel-microcode
          - libpam-ssh-agent-auth
          - nut-client
          - sudo
          - tar
          - vim
          - wget
        state: present
        update_cache: true

    # https://forum.proxmox.com/threads/tutorial-unprivileged-lxcs-mount-cifs-shares.101795/
    # - name: Add media share mount for use in LXC containers
    #   ansible.posix.mount:
    #     src: //10.0.10.16/media
    #     path: /mnt/lxc_shares/media/
    #     opts: _netdev,x-systemd.automount,noatime,uid=100000,gid=100900,dir_mode=0770,file_mode=0770,credentials=/root/media_share.creds
    #     fstype: cifs
    #     boot: true
    #     state: mounted
