- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: true

- name: Restart haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted
    enabled: true
