#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	DO
    $$
        BEGIN
            CREATE USER "${SPARKY_FITNESS_APP_DB_USER}" WITH PASSWORD '${SPARKY_FITNESS_APP_DB_PASSWORD}';
        EXCEPTION
            WHEN DUPLICATE_OBJECT THEN
                RAISE NOTICE 'app user already exists, skipping';
        END
    $$;

    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${SPARKY_FITNESS_APP_DB_USER}";
    GRANT USAGE ON SCHEMA public TO "${SPARKY_FITNESS_APP_DB_USER}";
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${SPARKY_FITNESS_APP_DB_USER}";
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "${SPARKY_FITNESS_APP_DB_USER}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${SPARKY_FITNESS_APP_DB_USER}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO "${SPARKY_FITNESS_APP_DB_USER}";
EOSQL