defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/qbittorrent
          tag: 5.1.2
        env:
          - name: TZ
            value: America/New_York
        securityContext:
          runAsUser: 568
          runAsGroup: 568

      gluetun:
        dependsOn: main
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.40.0
        env:
          - name: VPN_SERVICE_PROVIDER
            value: private internet access
          - name: SERVER_REGIONS
            value: Sweden,Switzerland,Netherlands
          - name: PORT_FORWARD_ONLY
            value: true
          - name: VPN_PORT_FORWARDING
            value: on
          - name: FIREWALL_INPUT_PORTS
            value: 8080
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: 172.16.0.0/12,192.168.0.0/16
          - name: TZ
            value: America/New_York
        envFrom:
          - secretRef:
              name: dev-vpn-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      port-forward:
        dependsOn: gluetun
        image:
          repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
          tag: 1.3
        env:
          - name: QBITTORRENT_SERVER
            value: localhost
          - name: QBITTORRENT_PORT
            value: 8080
          - name: PORT_FORWARDED
            value: "/tmp/gluetun/forwarded_port"

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8080

persistence:
  config:
    existingClaim: qbittorrent-config
    advancedMounts:
      main:
        main:
          - path: /config
  # Configure an emptyDir to share the port-forwarding location between containers
  gluetun-data:
    type: emptyDir
    advancedMounts:
      main:
        gluetun:
          - path: /tmp/gluetun
        port-forward:
          - path: /tmp/gluetun
            readOnly: true
