apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: kube.squatch.dev/dev-qbittorrent.vpn-secret
        property: OPENVPN_USER
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: kube.squatch.dev/dev-qbittorrent.vpn-secret
        property: OPENVPN_PASSWORD
